package proyectosniffer;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.jnetpcap.packet.JPacket;

public class Info extends javax.swing.JFrame {
     ArrayList<JPacket> tramas = new ArrayList<>();
    
    /**
     * Creates new form Info
     * @param tramas
     */
    public Info(ArrayList<JPacket> tramas) {
        this.tramas = tramas;
        initComponents(); 
        jLabelIP.setVisible(false);
        jScrollPaneIP.setVisible(false);
        jLabelTipo.setVisible(false);
        jScrollPaneTipo.setVisible(false);
    }
    
    
  //  @Override
   /* public Image getIconImage(){
        Image im = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo.png"));
        return im;
    }
    */
    /**
     *This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jScrollPaneTipo = new javax.swing.JScrollPane();
        jTextAreaTipo = new javax.swing.JTextArea();
        jLabelTipo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonAplicar = new javax.swing.JButton();
        jScrollPaneIP = new javax.swing.JScrollPane();
        jTextAreaIP = new javax.swing.JTextArea();
        jLabelIP = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jTextFieldNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaProtocolo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 0, 0));
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAreaTipo.setEditable(false);
        jTextAreaTipo.setBackground(new java.awt.Color(51, 51, 51));
        jTextAreaTipo.setColumns(20);
        jTextAreaTipo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jTextAreaTipo.setForeground(new java.awt.Color(0, 153, 255));
        jTextAreaTipo.setRows(5);
        jScrollPaneTipo.setViewportView(jTextAreaTipo);

        getContentPane().add(jScrollPaneTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 420, 250));

        jLabelTipo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(51, 51, 51));
        jLabelTipo.setText("Información Tipo:");
        getContentPane().add(jLabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 230, 30));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Información de las tramas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 520, 30));

        jButtonAplicar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonAplicar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButtonAplicar.setForeground(new java.awt.Color(51, 51, 51));
        jButtonAplicar.setText("Buscar Trama");
        jButtonAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 190, 30));

        jTextAreaIP.setEditable(false);
        jTextAreaIP.setBackground(new java.awt.Color(51, 51, 51));
        jTextAreaIP.setColumns(20);
        jTextAreaIP.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jTextAreaIP.setForeground(new java.awt.Color(0, 153, 255));
        jTextAreaIP.setRows(5);
        jScrollPaneIP.setViewportView(jTextAreaIP);

        getContentPane().add(jScrollPaneIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 420, 250));

        jLabelIP.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabelIP.setForeground(new java.awt.Color(51, 51, 51));
        jLabelIP.setText("Información Protocolo IP:");
        getContentPane().add(jLabelIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 260, 30));

        jButtonSalir.setBackground(new java.awt.Color(51, 51, 51));
        jButtonSalir.setForeground(new java.awt.Color(0, 153, 255));
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 0, 40, 20));

        jTextFieldNum.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldNum.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jTextFieldNum.setForeground(new java.awt.Color(0, 153, 255));
        jTextFieldNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 50, -1));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Información Protocolo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 230, 30));

        jTextAreaProtocolo.setEditable(false);
        jTextAreaProtocolo.setBackground(new java.awt.Color(51, 51, 51));
        jTextAreaProtocolo.setColumns(20);
        jTextAreaProtocolo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jTextAreaProtocolo.setForeground(new java.awt.Color(0, 153, 255));
        jTextAreaProtocolo.setRows(5);
        jScrollPane1.setViewportView(jTextAreaProtocolo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 420, 250));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Número de trama:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 170, 30));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 240, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jTextFieldNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumActionPerformed

    private void jButtonAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarActionPerformed
        jLabelIP.setVisible(false);
        jScrollPaneIP.setVisible(false);
        jLabelTipo.setVisible(false);
        jScrollPaneTipo.setVisible(false);
        try{
            int num = Integer.parseInt(jTextFieldNum.getText());
            if(num>0 && num<tramas.size())
                llenarProtocolo(num);
                
            else
                JOptionPane.showMessageDialog(this, "No existe la trama "+jTextFieldNum.getText(), "ERROR", JOptionPane.ERROR_MESSAGE); // mostramos un mensaje (frame, mensaje)
        }catch(Exception e){
           System.out.println(e);
        }
    }//GEN-LAST:event_jButtonAplicarActionPerformed
    
    private void llenarProtocolo(int n){
        
        String Cadtipo = "";
        String mensaje = "";
        String aux="";
        String protocolo="";
        String origen, destino;
        
        int tipo = (tramas.get(n).getUByte(12) * 256 ) + (tramas.get(n).getUByte(13));
        if(tipo > 1500) { // Ethernet
            Cadtipo = "Tipo: Ethernet";
            jLabelTipo.setVisible(true);
            jScrollPaneTipo.setVisible(true);
            if(tipo == 2048) { //IP
                String IP = "Tipo IP\n";
                IPv4 ipv4 = new IPv4(tramas.get(n));
                IP += ipv4.llenarIPv4();
                int protocol = ipv4.getProtocoloIP();
                int indice = ipv4.getIndice();
                jTextAreaTipo.setText(IP);
                
                ProtocoloIP protocoloip = new ProtocoloIP(protocol, tramas.get(n), indice);
                String ipProtocol = protocoloip.llenaProtocoloIP();
                jLabelIP.setVisible(true);
                jScrollPaneIP.setVisible(true);
                jTextAreaIP.setText(ipProtocol);
            } else if(tipo == 2054) {
                ARP arp = new ARP(tramas.get(n));
                String a = "Tipo ARP\n";
                a+= arp.llenaARP();
                jTextAreaTipo.setText(a);
            }
        }
        else { // IEEE
            IEEE ieee = new IEEE(tramas.get(n));
            Cadtipo = "Tipo: IEEE 802.3";
            protocolo = ieee.llenarIeee(n);
        }
        for (int i = 6; i < 12; i++) {   //MAC ORIGEN
            aux = aux.concat(String.format("%02X", tramas.get(n).getUByte(i)));
            aux = aux.concat(" ");
        }
        origen = aux;
        aux = "";
        for (int i = 0; i < 6; i++) { //MAC destino
            aux = aux.concat(String.format("%02X", tramas.get(n).getUByte(i)));
            aux = aux.concat(" ");
        }
        destino = aux;
        mensaje = Cadtipo+" (0x"+Integer.toHexString(tipo)+")\nMAC origen: "+origen+"\nMAC destino: "+destino+"\n"+protocolo;
        jTextAreaProtocolo.setText(mensaje);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAplicar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelIP;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneIP;
    private javax.swing.JScrollPane jScrollPaneTipo;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextAreaIP;
    private javax.swing.JTextArea jTextAreaProtocolo;
    private javax.swing.JTextArea jTextAreaTipo;
    private javax.swing.JTextField jTextFieldNum;
    // End of variables declaration//GEN-END:variables
}
